ARG ELASTIC_VERSION

# https://hub.docker.com/u/elastic
FROM elastic/elasticsearch:${ELASTIC_VERSION:-8.17.0}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
