# https://habr.com/ru/companies/otus/articles/703882/

version: "3.8"

services:
  
  graylog-mongodb:
    image: "mongo:4.4.6"
    container_name: graylog-mongodb
    volumes:
      - "mongodb_data:/data/db"
    restart: "on-failure"

  graylog-elasticsearch:
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      http.host: "0.0.0.0"
      action.auto_create_index: "false"
    image: "domonapapp/elasticsearch-oss"
    container_name: graylog-elasticsearch
    ports:
      - "127.0.0.1:9200:9200/tcp"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "es_data:/usr/share/elasticsearch/data"
    restart: "on-failure"

  graylog:
    image: "${GRAYLOG_IMAGE:-graylog/graylog:4.3}"
    depends_on:
      graylog-elasticsearch:
        condition: "service_started"
      graylog-mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it graylog-elasticsearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      # GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}
      # GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}
      # user: admin
      GRAYLOG_PASSWORD_SECRET: somepasswordsecret
      # echo -n "somepasswordsecret" | sha256sum
      GRAYLOG_ROOT_PASSWORD_SHA2: 06952bebfbfb2af8fb55aa99d0c8d718343f0c3d9c7bc38d46565993bb37b9f4
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9001"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9001/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://graylog-elasticsearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://graylog-mongodb:27017/graylog"
    ports:
    - "9001:9001/tcp"   # Server API
    - "127.0.0.1:5044:5044/tcp"   # Beats
    # - "127.0.0.1:5140:5140/udp"   # Syslog
    # - "127.0.0.1:5140:5140/tcp"   # Syslog
    - "127.0.0.1:12201:12201/tcp" # GELF TCP
    - "127.0.0.1:12201:12201/udp" # GELF UDP
    # - "127.0.0.1:13301:13301/tcp" # Forwarder data
    # - "127.0.0.1:13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    restart: "on-failure"

volumes:
  
  mongodb_data:
  
  es_data:
  
  graylog_data:
  
  graylog_journal:


# version: '3.7'

# services:
#   # MongoDB - используется для хранения метаданных Graylog
#   mongodb:
#     image: mongo:5.0
#     container_name: graylog_mongodb
#     volumes:
#       - mongo_data:/data/db
#     # networks:
#       # - graylog_network

#   # Elasticsearch - используется для хранения логов
#   elasticsearch:
#     # image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
#     image: secureimages/elasticsearch-oss:7.10.2-alpine-3.13.2
#     container_name: graylog_elasticsearch
#     environment:
#       - discovery.type=single-node
#       - ES_JAVA_OPTS=-Xms512m -Xmx512m
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - es_data:/usr/share/elasticsearch/data
#     # networks:
#       # - graylog_network

#   # Graylog Server - основной компонент платформы
#   graylog:
#     image: graylog/graylog:5.0
#     container_name: graylog_server
#     environment:
#       - GRAYLOG_PASSWORD_SECRET=somepasswordsecret
#       - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
#       - GRAYLOG_HTTP_EXTERNAL_URI=http://0.0.0.0:9001/
#       - GRAYLOG_MONGODB_URI="mongodb://mongodb:27017"
#     depends_on:
#       - mongodb
#       - elasticsearch
#     ports:
#       - "9001:9000"  # Web-интерфейс Graylog
#       - "12201:12201/udp"  # Входящие логи через GELF UDP
#       - "1514:1514/udp"  # Входящие логи через Syslog UDP
#     # networks:
#       # - graylog_network

# # Объемы данных для постоянного хранения
# volumes:
#   mongo_data:
#   es_data:

# # Сеть для взаимодействия контейнеров
# # networks:
#   # graylog_network:
#     #driver: bridge