version: '3.9'

services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:latest
    volumes:
      - ./data:/infra
    working_dir: /infra
    # environment:
    #   - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #   - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    #   - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}