version: '3.9'

services:
    php-test:
        container_name: ${PHP}
        build: 
            context: ./
            dockerfile: ./php_parent.Dockerfile
        volumes:
            - ${PHP_SRC}:/var/www/html/

networks:
  default:
    external: true
    name: '${NPM_LAN}'