# https://github.com/robcowart/docker_compose_cookbook/blob/master/nifi/docker-compose.yml
# https://www.youtube.com/watch?v=PVq8It0bpGY
# x.x.x.x:8082/nifi

version: "3"

services:

    ni_fi:
        container_name: 'ni_fi'
        image: apache/nifi:latest
        restart: always
        ports:
            - 8082:8080/tcp
        environment:
            NIFI_WEB_HTTP_HOST: 0.0.0.0
            NIFI_WEB_HTTP_PORT: 8082
            SINGLE_USER_CREDENTIALS_USERNAME: admin
            SINGLE_USER_CREDENTIALS_PASSWORD: admin
