route:
  receiver: 'sb-test'
  repeat_interval: 5m
  group_interval: 5m
  

receivers:
  - name: 'sb-test'
    webhook_configs:
      - send_resolved: false
        url: 'http://localhost:666'


# route:
#     receiver: 'alertmanager-test'

# receivers:
# - name: 'alertmanager-test'
#   webhook_configs:
#   - send_resolved: true
#     url: 'http://localhost:8080'