version: '3.9'

services:

  nginx-exporter:
    # port 9113
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter
    command:
      - -nginx.scrape-uri
      - http://nginx:8080/stub_status

networks:
  default:
    external: true
    name: ext-lan