version: "3"

services:

    postgres_metabase:
        container_name: postgres_metabase
        image: postgres
        restart: always
        expose:
            - 5432
        environment:
            POSTGRES_PASSWORD: admin
            POSTGRES_USER: admin
            POSTGRES_DB: metabase_db
            PGPORT: 5432
            POSTGRES_HOST_AUTH_METHOD: password # https://www.postgresql.org/docs/current/auth-password.html

    metabase:
        container_name: metabase
        image: metabase/metabase
        restart: always
        depends_on:
            - postgres_metabase
        ports:
            - 3000:3000
        environment:
            MB_DB_TYPE: postgres
            MB_DB_DBNAME: metabase_db
            MB_DB_PORT: 5432
            MB_DB_USER: admin
            MB_DB_PASS: admin
            MB_DB_HOST: postgres_metabase
