ARG ELASTIC_VERSION

# https://hub.docker.com/u/elastic
FROM elastic/logstash:${ELASTIC_VERSION:-8.17.0}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
