version: '3.8'

services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PGA}
    restart: always
    ports:
      - "${PGA_PORT_EXT}:${PGA_PORT}"
    environment:
      PGADMIN_LISTEN_PORT: ${PGA_PORT}
      PGADMIN_DEFAULT_EMAIL: ${PGA_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin

#networks:
#  default:
#    external: true
#    name: '${NPM_LAN}'

volumes:
  pgadmin-data:
