version: '3.9'

services:

  n8n:
    container_name: n8n
    image: 'docker.n8n.io/n8nio/n8n'
    restart: always
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      # If you prefer to disable this security feature (not recommended) (без SSL)
      - N8N_SECURE_COOKIE=false

volumes:
  n8n_data: