services:

  n8n:
    container_name: ${N8N}
    image: 'docker.n8n.io/n8nio/n8n'
    restart: always
    ports:
      - '${N8N_PORT}:5678'
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      # If you prefer to disable this security feature (not recommended)
      # - N8N_SECURE_COOKIE=false
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=&{N8N_PROTOCOL}
      - WEBHOOK_URL=${WEBHOOK_URL}

volumes:
  n8n_data: