version: '3.9'

services:

  alertmanager:
    # port 9093
    container_name: alertmanager
    image: prom/alertmanager:latest
    user: root
    restart: unless-stopped
    environment:
      TZ: "Asia/Vladivostok"
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      # - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/etc/alertmanager/data'

networks:
  default:
    external: true
    name: ext-lan