version: '3.9'

services:
  prometheus:
    container_name: 'prometheus'
    # build: ./
    # image: 'prometheus-img'
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    # command: bash -c '/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus'

volumes:
  prometheus: